[package]
name = "run_simulations"
version = "0.1.0"
edition = "2021"

[dependencies]
objects = {path = "../../libs/objects"}
vector = {path = "../../libs/vector"}
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15.0"